services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - profile
      - sponsor

  profile:
    build:
      context: .
      dockerfile: profile/Dockerfile
    ports:
      - "6501:6501"
    expose:
      - "6501"

  sponsor:
    build:
      context: .
      dockerfile: sponsor/Dockerfile
    ports:
      - "6502:6502"
    expose:
      - "6502"
