services:
  gateway:
    image: "chornge.io/portfolio-gateway:main"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - profile
      - sponsor

  profile:
    image: "chornge.io/portfolio-profile:main"
    build:
      context: .
      dockerfile: profile/Dockerfile
    ports:
      - "6501:6501"

  sponsor:
    image: "chornge.io/portfolio-sponsor:main"
    build:
      context: .
      dockerfile: sponsor/Dockerfile
    ports:
      - "6502:6502"
